[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "af20ce6ff6597b0a83bfdd4cc3a9aba2593e691f"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "cf3c82002dd3b15b47cb220eff021ee3008ed0499550d20de04b6a5b21d7e0c4"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+1/Pixman.v0.38.4.x86_64-linux-gnu.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "635043ae37613874ec147e26adf9becd2a41d906"
os = "macos"

    [[Pixman.download]]
    sha256 = "ef915b1c1ebc0d6b3a61dc058dfecfec0cff05663f7288db83461862022a0c13"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+1/Pixman.v0.38.4.x86_64-apple-darwin14.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "62d9b0a679d2557b866a90d427f242b067e961b2"
os = "windows"

    [[Pixman.download]]
    sha256 = "f0d6a8d30457d9d3ff99069d7d449be7f10742646e693b69273df22283a7abce"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+1/Pixman.v0.38.4.i686-w64-mingw32.tar.gz"
[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "fe23ac535e9991d60c3f2b609f61fceaa116f271"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "d0c3311012fbd05449d64d01fbb429ffd62136caee86e9eee4a792d7222c4edc"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+1/Pixman.v0.38.4.aarch64-linux-gnu.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "681a556a4d1ee0f0782811135884b12ad0a7c1c8"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "f20a2fbb52d4043c8615cd2d5d0f8bebf8f8620cbbc3552d88d91d3453be8e41"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+1/Pixman.v0.38.4.i686-linux-musl.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "14f26b2f89c0cc1fcbc2e672b038841b40b5f8f4"
os = "windows"

    [[Pixman.download]]
    sha256 = "60a1ac4fbfd75d0191e75242137929afe377804f1eb92bf5d3e146c073751f4e"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+1/Pixman.v0.38.4.x86_64-w64-mingw32.tar.gz"
[[Pixman]]
arch = "powerpc64le"
git-tree-sha1 = "8044c4b46e486c77b12d49152f8a2cdb2c0a9347"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "18145abe2c4f8b78aae5b15071c214a8d9d3a7d4c4f460dc76c81847af5c3456"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+1/Pixman.v0.38.4.powerpc64le-linux-gnu.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "47728555af3a6e7c45c0ac1348d3dd34af54f256"
os = "freebsd"

    [[Pixman.download]]
    sha256 = "57601a037623b7cda6414b209ba8886a4f34bb029a2de9ef0bcbf2848e4b371c"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+1/Pixman.v0.38.4.x86_64-unknown-freebsd11.1.tar.gz"
[[Pixman]]
arch = "armv7l"
git-tree-sha1 = "0874ea44cd14e167ec14b4ccfc12ed37a8738c7a"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "06ea92cc17cb7dccaf0b81699ecc1f560b0cf35a160f5268f544659a4b02cb44"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+1/Pixman.v0.38.4.arm-linux-musleabihf.tar.gz"
[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "59f8049931913d41f629d94b85b3e00e386ab395"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "1a6d8f0705b232bc375b7d8981475b91760c6c02e297ca8b1a5ee5c1477d82f1"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+1/Pixman.v0.38.4.aarch64-linux-musl.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "83bf0fc669bf20c1cdf8fa62f7ff43e55e56cc05"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "f2d8edb3e59dcedd0e7c41fd31fff8561b703b73000f4ae5b5e4fc4c2eb6caf7"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+1/Pixman.v0.38.4.i686-linux-gnu.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "7fef98add2f8ef15478ece5a786359900626dd74"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "67cb023d77223f0eecddaefcd13480722f8185c49ba3c911522d48a2ccce4b69"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+1/Pixman.v0.38.4.x86_64-linux-musl.tar.gz"
[[Pixman]]
arch = "armv7l"
git-tree-sha1 = "00925b1a6cf823784e0b37c314e3fd7aaae13478"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "f799396e398ca5d7dc944c0c5c7752345b8c92be44d8babd987d0e579ae5bf52"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+1/Pixman.v0.38.4.arm-linux-gnueabihf.tar.gz"
